NAME  : VISHWAKARMA POOJA RAMASHANKAR
SR.NO : 00-0-0-40-52-22-1-21633

Steps performed:
1. Manually collected data: water_leakage.xlsx :: Leak id and surrounding 6 meters data from QGIS tool
i.e. data/water_leakage.xlsx
2. Aggregate the data to include the leak ID and all six meter IDs in the dataframe i.e. data/WaterLekageDF.csv
3. Divided the Excel workbook into individual sheets with name of each meter ID, where each sheet corresponds to a unique Leak ID, and included a column indicating the meter IDs. i.e. data/SplitMeterIDFiles
4. Generated a CSV file for each Leak ID containing comprehensive details such as 'Date', 'Time', 'Flow Rate (mᶾ/hr)', 'Net Flow (mᶾ)', 'Pressure (m)', and 'Meter ID'. i.e. data/RawLeakData

In [1]:
# Importing libraries
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from datetime import datetime

In [2]:
# Manually collected data :: Leak id and surrounding 6 meters data from QGIS tool 
# i.e. data/water_leakage.xlsx

df = pd.read_excel("data/water_leakage.xlsx")
WaterLekageDF = pd.DataFrame(df[["id", "date_leak_", "metre_1", "meter_2", "meter_3", "meter_4", "meter_5", "meter_6"]])
# Dropping duplicate rows based on 'id' column
WaterLekageDF.drop_duplicates(subset='id', inplace=True)
#print(WaterLekageDF)

input_format = "%Y-%m-%d %I:%M %p"
output_format = "%Y-%m-%d %H:%M:%S"

def convert_date(date_str):
    if isinstance(date_str, str):
        date_str = date_str.upper()
        # Replace "A.M." and "P.M." with "AM" and "PM" respectively
        date_str = date_str.replace(" A.M.", " AM").replace(" P.M.", " PM")
        # Parsing the date string into a datetime object
        date_obj = datetime.strptime(date_str, input_format)
        formatted_date = date_obj.strftime(output_format)
        return formatted_date
    else:
        return date_str
WaterLekageDF['date_leak_'] = WaterLekageDF['date_leak_'].apply(lambda x: convert_date(x))
# print(WaterLekageDF['date_leak_'])
WaterLekageDF['date_leak_'] = pd.to_datetime(WaterLekageDF['date_leak_'])
WaterLekageDF.insert(2, 'time', WaterLekageDF['date_leak_'].dt.strftime('%H:%M:%S'))
# Saving the DataFrame to a CSV file
WaterLekageDF.to_csv("data/WaterLekageDF.csv", index=False)
WaterLekageDF

,id,date_leak_,time,metre_1,meter_2,meter_3,meter_4,meter_5,meter_6
0,2377,2017-12-09 12:53:00,12:53:00,SE3DM0602,SE3DM0601,SE3DM0303,SE3DM0304,SE3DM0501,SE3DM0401
1,2721,2017-12-14 11:01:00,11:01:00,SE3DM0602,SE3DM0601,SE3DM0303,SE3DM0304,SE3DM0501,SE3DM0401
4,4820,2018-01-27 17:55:00,17:55:00,SE3DM0301,SE3DM0302,SE3DM0802,SE3DM0801,SE3DM0401,SE3DM0501
5,4814,2018-01-27 16:37:00,16:37:00,SE3DM0301,SE3DM0302,SE3DM0802,SE3DM0801,SE3DM0401,SE3DM0501
6,1304,2017-11-22 13:38:00,13:38:00,SE3DM0301,SE3DM0302,SE3DM0802,SE3DM0801,SE3DM0401,SE3DM0501
7,4209,2018-01-11 13:50:00,13:50:00,SE3DM0702,SE3DM0703,SE3DM0701,SE3DM1202,SE3DM1301,SE3DM0704
8,4205,2018-01-11 11:18:00,11:18:00,SE3DM0702,SE3DM0703,SE3DM0701,SE3DM1202,SE3DM1301,SE3DM0704
9,4344,2018-01-16 14:58:00,14:58:00,SE3DM0702,SE3DM0703,SE3DM0701,SE3DM1202,SE3DM1301,SE3DM0704
13,2464,2017-12-11 12:20:00,12:20:00,SE3DM0202,S3DM0805,SE3DM0101,SW4SM0701,SW4SM0702,S3DM0804
14,3925,2018-01-06 00:02:00,00:02:00,SE3DM0202,S3DM0805,SE3DM0101,SW4SM0701,SW4SM0702,S3DM0804
15,5956,2018-02-21 03:07:00,03:07:00,S3DM0501,S3DM0201,S3DM0202,S3DM0304,S3DM0502,S3DM0605
16,563,2017-11-09 00:30:00,00:30:00,S3DM0501,S3DM0201,S3DM0202,S3DM0304,S3DM0502,S3DM0605
17,5018,2018-01-31 17:04:00,17:04:00,S3DM0501,S3DM0201,S3DM0202,S3DM0304,S3DM0502,S3DM0605
18,269,2017-11-04 11:16:00,11:16:00,S3DM0501,S3DM0201,S3DM0202,S3DM0304,S3DM0502,S3DM0605
19,272,2017-11-04 11:21:00,11:21:00,S3DM0303,S3DM0601,S3DM0605,S3DM0502,S3DM0503,S3DM0302
20,53,2017-10-30 17:25:00,17:25:00,SW4SM1101,SW4SM1103,SW4DM0502,SW4DM1102,SW4DM0301,SW4DM0201
21,794,2017-11-13 10:18:00,10:18:00,SW4SM1101,SW4SM1103,SW4DM0502,SW4DM1102,SW4DM0301,SW4DM0201
22,494,2017-11-08 09:56:00,09:56:00,SW4SM1101,SW4SM1103,SW4DM0502,SW4DM1102,SW4DM0301,SW4DM0201
23,547,2017-11-08 16:39:00,16:39:00,SW4SM1101,SW4SM1103,SW4DM0502,SW4DM1102,SW4DM0301,SW4DM0201
24,3730,2018-01-02 12:43:00,12:43:00,S2DM0202,S2DM0201,S2DM0102,S2DM0203,SW4DM0104,SW4DM0103
25,3714,2018-01-01 14:17:00,14:17:00,S2DM0202,S2DM0201,S2DM0102,S2DM0203,SW4DM0104,SW4DM0103
26,3766,2018-01-02 23:35:00,23:35:00,S2DM0202,S2DM0201,S2DM0102,S2DM0203,SW4DM0104,SW4DM0103
27,3733,2018-01-02 13:23:00,13:23:00,S2DM0202,S2DM0201,S2DM0102,S2DM0203,SW4DM0104,SW4DM0103
28,4827,2018-01-28 00:00:00,00:00:00,S2DM0202,S2DM0201,S2DM0102,S2DM0203,SW4DM0104,SW4DM0103
29,3168,2017-12-21 17:22:00,17:22:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
30,479,2017-11-08 09:03:00,09:03:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
31,719,2017-11-10 16:11:00,16:11:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
32,713,2017-11-10 15:38:00,15:38:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
33,585,2017-11-09 09:49:00,09:49:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
34,3912,2018-01-05 16:21:00,16:21:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
35,4034,2018-01-08 16:03:00,16:03:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
36,3999,2018-01-08 09:21:00,09:21:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
37,3265,2017-12-22 20:26:00,20:26:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
38,7248,2018-03-24 18:07:00,18:07:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
39,7615,2018-03-29 14:06:00,14:06:00,S2DM0203,SW4DM0104,SW4DM0103,SW4DM0102,SW4DM0101,S1DM1003
40,6999,2018-03-17 14:57:00,14:57:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
41,284,2017-11-04 12:28:00,12:28:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
42,5780,2018-02-17 02:04:00,02:04:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
43,239,2017-11-04 02:55:00,02:55:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
44,927,2017-11-15 11:12:00,11:12:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
45,3350,2017-12-25 11:03:00,11:03:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
46,4378,2018-01-17 15:52:00,15:52:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
47,3643,2017-12-29 16:44:00,16:44:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
48,3465,2017-12-27 14:38:00,14:38:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201
49,1299,2017-11-23 00:51:00,00:51:00,SW2DM1001,SW2DM1001,SW2DM1102,SW2DM1008,SW2DM1101,SW2SM1201

In [3]:
def split_workbook_and_add_meter_id(input_file):
    output_dir = "data/SplitMeterIDFiles"    # Output files
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Reading the Excel file with skipping the first two rows (index 0 and 1) as they contain headers
    xls = pd.ExcelFile(input_file)
    sheet_names = xls.sheet_names
    for sheet_name in sheet_names:
        last_word = sheet_name.split()[-1]
        df = pd.read_excel(input_file, sheet_name=sheet_name, header=1)  # Specifying header row index
        # Adding a new column with Meter ID to the DataFrame
        df['Meter ID'] = last_word
        output_file = os.path.join(output_dir, f"{last_word}.xlsx")
        df.to_excel(output_file, index=False)
        print(f"Sheet '{sheet_name}' saved to '{output_file}' with Meter ID '{last_word}'")

# Provide the path to your input Excel file
input_file = "data/83DMAS.xlsx"
split_workbook_and_add_meter_id(input_file)
print("All sheets processed successfully.")

# Removing the specified files if they exist (data cleaning)
files_to_remove = [
    "data/SplitMeterIDFiles/Byatarayanap.xlsx",
    "data/SplitMeterIDFiles/Nagar.xlsx",
    "data/SplitMeterIDFiles/KRMarketChamarajpeteSW1DM0602.xlsx",
    "data/SplitMeterIDFiles/KRMarketChamarajpeteSW1DM0603.xlsx",
    "data/SplitMeterIDFiles/KRMarketChamarajpeteSW1SM0607.xlsx",
    "data/SplitMeterIDFiles/KRMarketChamarajpeteSW1SM0606.xlsx",
    "data/SplitMeterIDFiles/SW3toSW1.xlsx",
    "data/SplitMeterIDFiles/Sheet33.xlsx"
]

for file in files_to_remove:
    if os.path.exists(file):
        os.remove(file)
        print(f"File '{file}' removed.")

Sheet 'Avalahalli & Byatarayanap' saved to 'data/SplitMeterIDFiles/Byatarayanap.xlsx' with Meter ID 'Byatarayanap'
Sheet 'Ashok Nagar' saved to 'data/SplitMeterIDFiles/Nagar.xlsx' with Meter ID 'Nagar'
Sheet 'Ashok Nagar SW3DM0604' saved to 'data/SplitMeterIDFiles/SW3DM0604.xlsx' with Meter ID 'SW3DM0604'
Sheet 'Ashok Nagar SW3DM0601' saved to 'data/SplitMeterIDFiles/SW3DM0601.xlsx' with Meter ID 'SW3DM0601'
Sheet 'Ashok Nagar SW3DM0602.' saved to 'data/SplitMeterIDFiles/SW3DM0602..xlsx' with Meter ID 'SW3DM0602.'
Sheet 'Ashok Nagar SW3DM0603' saved to 'data/SplitMeterIDFiles/SW3DM0603.xlsx' with Meter ID 'SW3DM0603'
Sheet 'Azad Nagar SW1DM1201' saved to 'data/SplitMeterIDFiles/SW1DM1201.xlsx' with Meter ID 'SW1DM1201'
Sheet 'Azad Nagar SW1DM1202' saved to 'data/SplitMeterIDFiles/SW1DM1202.xlsx' with Meter ID 'SW1DM1202'
Sheet 'Azad Nagar SW1DM1203' saved to 'data/SplitMeterIDFiles/SW1DM1203.xlsx' with Meter ID 'SW1DM1203'
Sheet 'Banagiri Nagar SW2DM0703' saved to 'data/SplitMeterIDFiles/SW2DM0703.xlsx' with Meter ID 'SW2DM0703'
Sheet 'Banagiri Nagar SW2DM0701' saved to 'data/SplitMeterIDFiles/SW2DM0701.xlsx' with Meter ID 'SW2DM0701'
Sheet 'Banagiri Nagar SW2DM0702' saved to 'data/SplitMeterIDFiles/SW2DM0702.xlsx' with Meter ID 'SW2DM0702'
Sheet 'Banashankari2nd stage SW2DM1001' saved to 'data/SplitMeterIDFiles/SW2DM1001.xlsx' with Meter ID 'SW2DM1001'
Sheet 'Banashankari2nd stage SW2DM1002' saved to 'data/SplitMeterIDFiles/SW2DM1002.xlsx' with Meter ID 'SW2DM1002'
Sheet 'Banashankari2nd stage SW2DM1003' saved to 'data/SplitMeterIDFiles/SW2DM1003.xlsx' with Meter ID 'SW2DM1003'
Sheet 'Banashankari2nd stage SW2DM1004' saved to 'data/SplitMeterIDFiles/SW2DM1004.xlsx' with Meter ID 'SW2DM1004'
Sheet 'Banashankari2nd stage SW2DM1006' saved to 'data/SplitMeterIDFiles/SW2DM1006.xlsx' with Meter ID 'SW2DM1006'
Sheet 'Banashankari2nd stage SW2DM1005' saved to 'data/SplitMeterIDFiles/SW2DM1005.xlsx' with Meter ID 'SW2DM1005'
Sheet 'Banashankari2nd stage SW2DM1007' saved to 'data/SplitMeterIDFiles/SW2DM1007.xlsx' with Meter ID 'SW2DM1007'
Sheet 'Banashankari2nd stage SW2DM1008' saved to 'data/SplitMeterIDFiles/SW2DM1008.xlsx' with Meter ID 'SW2DM1008'
Sheet 'Basavanagudi SW3DM1001' saved to 'data/SplitMeterIDFiles/SW3DM1001.xlsx' with Meter ID 'SW3DM1001'
Sheet 'Basavanagudi SW3DM1003' saved to 'data/SplitMeterIDFiles/SW3DM1003.xlsx' with Meter ID 'SW3DM1003'
Sheet 'Basavangudi SW3toSW1' saved to 'data/SplitMeterIDFiles/SW3toSW1.xlsx' with Meter ID 'SW3toSW1'
Sheet 'Bandre nagar S1DM0402' saved to 'data/SplitMeterIDFiles/S1DM0402.xlsx' with Meter ID 'S1DM0402'
Sheet 'Bendre Nagar S1DM0401' saved to 'data/SplitMeterIDFiles/S1DM0401.xlsx' with Meter ID 'S1DM0401'
Sheet 'Bendre Nagar S1DM0403' saved to 'data/SplitMeterIDFiles/S1DM0403.xlsx' with Meter ID 'S1DM0403'
Sheet 'BHCS Layout S1DM0701' saved to 'data/SplitMeterIDFiles/S1DM0701.xlsx' with Meter ID 'S1DM0701'
Sheet 'BHCS Layout  S1DM0702 ' saved to 'data/SplitMeterIDFiles/S1DM0702.xlsx' with Meter ID 'S1DM0702'
Sheet 'BHCS Layout  S1DM0703' saved to 'data/SplitMeterIDFiles/S1DM0703.xlsx' with Meter ID 'S1DM0703'
Sheet 'Bhuvaneshwari Nagar SW2DM1601' saved to 'data/SplitMeterIDFiles/SW2DM1601.xlsx' with Meter ID 'SW2DM1601'
Sheet 'Byrasandra SW4DM0602' saved to 'data/SplitMeterIDFiles/SW4DM0602.xlsx' with Meter ID 'SW4DM0602'
Sheet 'Byrasandra SW4DM0601' saved to 'data/SplitMeterIDFiles/SW4DM0601.xlsx' with Meter ID 'SW4DM0601'
Sheet 'Byrasandra SW4DM0603' saved to 'data/SplitMeterIDFiles/SW4DM0603.xlsx' with Meter ID 'SW4DM0603'
Sheet 'Byrasandra SW4SM0602' saved to 'data/SplitMeterIDFiles/SW4SM0602.xlsx' with Meter ID 'SW4SM0602'
Sheet 'Byrasandra SW4SM0601' saved to 'data/SplitMeterIDFiles/SW4SM0601.xlsx' with Meter ID 'SW4SM0601'
Sheet 'CARP Quarters SE3DM0101' saved to 'data/SplitMeterIDFiles/SE3DM0101.xlsx' with Meter ID 'SE3DM0101'
Sheet 'Chalavadipalya&Chikkal C1DM0101' saved to 'data/SplitMeterIDFiles/C1DM0101.xlsx' with Meter ID 'C1DM0101'
Sheet 'Chalavadipalya&Chikkal C1DM0102' saved to 'data/SplitMeterIDFiles/C1DM0102.xlsx' with Meter ID 'C1DM0102'
Sheet 'Chalavadipalya&Chikkal C1DM0103' saved to 'data/SplitMeterIDFiles/C1DM0103.xlsx' with Meter ID 'C1DM0103'
Sheet 'Chalavadipalya&Chikkal C1DM0107' saved to 'data/SplitMeterIDFiles/C1DM0107.xlsx' with Meter ID 'C1DM0107'
Sheet 'Channammanakere SW2DM0602' saved to 'data/SplitMeterIDFiles/SW2DM0602.xlsx' with Meter ID 'SW2DM0602'
Sheet 'Channammanakere SW2DM0603' saved to 'data/SplitMeterIDFiles/SW2DM0603.xlsx' with Meter ID 'SW2DM0603'
Sheet 'Channammanakere SW2DM0601' saved to 'data/SplitMeterIDFiles/SW2DM0601.xlsx' with Meter ID 'SW2DM0601'
Sheet 'Channammanakere SW2DM0604' saved to 'data/SplitMeterIDFiles/SW2DM0604.xlsx' with Meter ID 'SW2DM0604'
Sheet 'Chikkalasandra S1DM0201' saved to 'data/SplitMeterIDFiles/S1DM0201.xlsx' with Meter ID 'S1DM0201'
Sheet 'Chikkalasandra S1DM0202' saved to 'data/SplitMeterIDFiles/S1DM0202.xlsx' with Meter ID 'S1DM0202'
Sheet 'Dollars Layout S2DM0101' saved to 'data/SplitMeterIDFiles/S2DM0101.xlsx' with Meter ID 'S2DM0101'
Sheet 'Dollars Layout S2DM0102' saved to 'data/SplitMeterIDFiles/S2DM0102.xlsx' with Meter ID 'S2DM0102'
Sheet 'Dwaraka Nagar SW2DM1301' saved to 'data/SplitMeterIDFiles/SW2DM1301.xlsx' with Meter ID 'SW2DM1301'
Sheet 'Ejipura&RaviTentArea SE3DM1001 ' saved to 'data/SplitMeterIDFiles/SE3DM1001.xlsx' with Meter ID 'SE3DM1001'
Sheet 'Eshwar Nagar S1DM0501' saved to 'data/SplitMeterIDFiles/S1DM0501.xlsx' with Meter ID 'S1DM0501'
Sheet 'GandhiBazar&NR Colony SW3DM0903' saved to 'data/SplitMeterIDFiles/SW3DM0903.xlsx' with Meter ID 'SW3DM0903'
Sheet 'GandhiBazar&NR Colony SW3DM0901' saved to 'data/SplitMeterIDFiles/SW3DM0901.xlsx' with Meter ID 'SW3DM0901'
Sheet 'GandhiBazar&NRColony SW3toSW1' saved to 'data/SplitMeterIDFiles/SW3toSW1.xlsx' with Meter ID 'SW3toSW1'
Sheet 'GavipumExt&Hanumanth SW3DM0501 ' saved to 'data/SplitMeterIDFiles/SW3DM0501.xlsx' with Meter ID 'SW3DM0501'
Sheet 'GavipumExt&Hanumanth SW3DM0502' saved to 'data/SplitMeterIDFiles/SW3DM0502.xlsx' with Meter ID 'SW3DM0502'
Sheet 'GavipumExt&Hanumanth SW3DM0503' saved to 'data/SplitMeterIDFiles/SW3DM0503.xlsx' with Meter ID 'SW3DM0503'
Sheet 'GavipumExt&Hanumanth SW3DM0505' saved to 'data/SplitMeterIDFiles/SW3DM0505.xlsx' with Meter ID 'SW3DM0505'
Sheet 'GavipumExt&Hanumanth SW3DM0506' saved to 'data/SplitMeterIDFiles/SW3DM0506.xlsx' with Meter ID 'SW3DM0506'
Sheet 'Giri Nagar SW2DM0201' saved to 'data/SplitMeterIDFiles/SW2DM0201.xlsx' with Meter ID 'SW2DM0201'
Sheet 'Giri Nagar SW2DM0202' saved to 'data/SplitMeterIDFiles/SW2DM0202.xlsx' with Meter ID 'SW2DM0202'
Sheet 'Giri Nagar SW2DM0204' saved to 'data/SplitMeterIDFiles/SW2DM0204.xlsx' with Meter ID 'SW2DM0204'
Sheet 'Giri Nagar SW2DM0205' saved to 'data/SplitMeterIDFiles/SW2DM0205.xlsx' with Meter ID 'SW2DM0205'
Sheet 'Giri Nagar SW2DM0203' saved to 'data/SplitMeterIDFiles/SW2DM0203.xlsx' with Meter ID 'SW2DM0203'
Sheet 'Gurappana Palya S3DM0601' saved to 'data/SplitMeterIDFiles/S3DM0601.xlsx' with Meter ID 'S3DM0601'
Sheet 'Gurappana Palya S3DM0602' saved to 'data/SplitMeterIDFiles/S3DM0602.xlsx' with Meter ID 'S3DM0602'
Sheet 'Gurappana Palya S3DM0603' saved to 'data/SplitMeterIDFiles/S3DM0603.xlsx' with Meter ID 'S3DM0603'
Sheet 'Gurappana Palya S3DM0604' saved to 'data/SplitMeterIDFiles/S3DM0604.xlsx' with Meter ID 'S3DM0604'
Sheet 'Gurappana Palya S3DM0605' saved to 'data/SplitMeterIDFiles/S3DM0605.xlsx' with Meter ID 'S3DM0605'
Sheet 'Gurappana Palya S3SM0601' saved to 'data/SplitMeterIDFiles/S3SM0601.xlsx' with Meter ID 'S3SM0601'
Sheet 'Gururaj Layout S1DM0101' saved to 'data/SplitMeterIDFiles/S1DM0101.xlsx' with Meter ID 'S1DM0101'
Sheet 'HombegowdaNagarNorth SW4DM1301 ' saved to 'data/SplitMeterIDFiles/SW4DM1301.xlsx' with Meter ID 'SW4DM1301'
Sheet 'Hombegowda NagarWest SW4DM1201' saved to 'data/SplitMeterIDFiles/SW4DM1201.xlsx' with Meter ID 'SW4DM1201'
Sheet 'Hombegowda NagarWest SW4DM1202' saved to 'data/SplitMeterIDFiles/SW4DM1202.xlsx' with Meter ID 'SW4DM1202'
Sheet 'Hombegowda NagarWest SW4DM1203' saved to 'data/SplitMeterIDFiles/SW4DM1203.xlsx' with Meter ID 'SW4DM1203'
Sheet 'Hombegowda NagarWest SW4DM1204' saved to 'data/SplitMeterIDFiles/SW4DM1204.xlsx' with Meter ID 'SW4DM1204'

Sheet 'Hombegowda NagarWest SW4SM1201' saved to 'data/SplitMeterIDFiles/SW4SM1201.xlsx' with Meter ID 'SW4SM1201'
Sheet 'HombegowdaNagarCent SW4DM0701 ' saved to 'data/SplitMeterIDFiles/SW4DM0701.xlsx' with Meter ID 'SW4DM0701'
Sheet 'HombegowdaNagarCent SW4SM0701 ' saved to 'data/SplitMeterIDFiles/SW4SM0701.xlsx' with Meter ID 'SW4SM0701'
Sheet 'HombegowdaNagarCent SW4SM0702' saved to 'data/SplitMeterIDFiles/SW4SM0702.xlsx' with Meter ID 'SW4SM0702'
Sheet 'Hosakerehalli SW2DM1403' saved to 'data/SplitMeterIDFiles/SW2DM1403.xlsx' with Meter ID 'SW2DM1403'
Sheet 'Hosakerehalli SW2DM1401' saved to 'data/SplitMeterIDFiles/SW2DM1401.xlsx' with Meter ID 'SW2DM1401'
Sheet 'Hosakerehalli SW2DM1402' saved to 'data/SplitMeterIDFiles/SW2DM1402.xlsx' with Meter ID 'SW2DM1402'
Sheet 'IAS Colony S3DM0202' saved to 'data/SplitMeterIDFiles/S3DM0202.xlsx' with Meter ID 'S3DM0202'
Sheet 'IAS Colony S3DM0201' saved to 'data/SplitMeterIDFiles/S3DM0201.xlsx' with Meter ID 'S3DM0201'
Sheet 'ISRO Layout S1DM0801' saved to 'data/SplitMeterIDFiles/S1DM0801.xlsx' with Meter ID 'S1DM0801'
Sheet 'ISRO Layout S1DM0802' saved to 'data/SplitMeterIDFiles/S1DM0802.xlsx' with Meter ID 'S1DM0802'
Sheet 'ITI Layout SW4DM0901' saved to 'data/SplitMeterIDFiles/SW4DM0901.xlsx' with Meter ID 'SW4DM0901'
Sheet 'Ittamadu SW2DM1501' saved to 'data/SplitMeterIDFiles/SW2DM1501.xlsx' with Meter ID 'SW2DM1501'
Sheet 'Ittamadu SW2DM1502' saved to 'data/SplitMeterIDFiles/SW2DM1502.xlsx' with Meter ID 'SW2DM1502'
Sheet 'J J Nagar SW1DM0903' saved to 'data/SplitMeterIDFiles/SW1DM0903.xlsx' with Meter ID 'SW1DM0903'
Sheet 'J J Nagar SW1DM0901' saved to 'data/SplitMeterIDFiles/SW1DM0901.xlsx' with Meter ID 'SW1DM0901'
Sheet 'J J Nagar SW1DM0902' saved to 'data/SplitMeterIDFiles/SW1DM0902.xlsx' with Meter ID 'SW1DM0902'
Sheet 'J J Nagar SW1SM0903' saved to 'data/SplitMeterIDFiles/SW1SM0903.xlsx' with Meter ID 'SW1SM0903'
Sheet 'Jakkasandra SE3DM0701' saved to 'data/SplitMeterIDFiles/SE3DM0701.xlsx' with Meter ID 'SE3DM0701'
Sheet 'Jakkasandra SE3DM0704' saved to 'data/SplitMeterIDFiles/SE3DM0704.xlsx' with Meter ID 'SE3DM0704'
Sheet 'Jakkasandra SE3DM0702' saved to 'data/SplitMeterIDFiles/SE3DM0702.xlsx' with Meter ID 'SE3DM0702'
Sheet 'Jakkasandra SE3DM0703' saved to 'data/SplitMeterIDFiles/SE3DM0703.xlsx' with Meter ID 'SE3DM0703'
Sheet 'Jayanagar 4th Block SW4DM0402' saved to 'data/SplitMeterIDFiles/SW4DM0402.xlsx' with Meter ID 'SW4DM0402'
Sheet 'Jayanagar 4th Block SW4DM0401' saved to 'data/SplitMeterIDFiles/SW4DM0401.xlsx' with Meter ID 'SW4DM0401'
Sheet 'Jayanaga 4thTblkS SW4DM1101  ' saved to 'data/SplitMeterIDFiles/SW4DM1101.xlsx' with Meter ID 'SW4DM1101'
Sheet 'Jayanaga 4thTblkS SW4DM1102 ' saved to 'data/SplitMeterIDFiles/SW4DM1102.xlsx' with Meter ID 'SW4DM1102'
Sheet 'Jayanaga 4thTblkS SW4DM1103' saved to 'data/SplitMeterIDFiles/SW4DM1103.xlsx' with Meter ID 'SW4DM1103'
Sheet 'Jayanaga 4thTblkS SW4SM1101' saved to 'data/SplitMeterIDFiles/SW4SM1101.xlsx' with Meter ID 'SW4SM1101'
Sheet 'Jayanaga 4thTblkS SW4SM1102' saved to 'data/SplitMeterIDFiles/SW4SM1102.xlsx' with Meter ID 'SW4SM1102'
Sheet 'Jayanaga 4thTblkS SW4SM1103' saved to 'data/SplitMeterIDFiles/SW4SM1103.xlsx' with Meter ID 'SW4SM1103'
Sheet 'JayanagaR4thTBlk(NE) SW4DM1001 ' saved to 'data/SplitMeterIDFiles/SW4DM1001.xlsx' with Meter ID 'SW4DM1001'
Sheet 'JayanagaR4thTBlk(NE) SW4DM1002 ' saved to 'data/SplitMeterIDFiles/SW4DM1002.xlsx' with Meter ID 'SW4DM1002'
Sheet 'JayanagaR4thTBlk(NE) SW4DM1003' saved to 'data/SplitMeterIDFiles/SW4DM1003.xlsx' with Meter ID 'SW4DM1003'
Sheet 'JayanagaR4thTBlk(NE) SW4DM1004' saved to 'data/SplitMeterIDFiles/SW4DM1004.xlsx' with Meter ID 'SW4DM1004'
Sheet 'Jayanagar4thTBlkC SW4DM0501' saved to 'data/SplitMeterIDFiles/SW4DM0501.xlsx' with Meter ID 'SW4DM0501'
Sheet 'Jayanagar4thTBlkC SW4DM0502' saved to 'data/SplitMeterIDFiles/SW4DM0502.xlsx' with Meter ID 'SW4DM0502'
Sheet 'Jayanagar7thBlk SW2DM1201' saved to 'data/SplitMeterIDFiles/SW2DM1201.xlsx' with Meter ID 'SW2DM1201'
Sheet 'Jayanagar7thBlk SW2DM1202' saved to 'data/SplitMeterIDFiles/SW2DM1202.xlsx' with Meter ID 'SW2DM1202'
Sheet 'JP Nagar 1st Phase SW4DM0101' saved to 'data/SplitMeterIDFiles/SW4DM0101.xlsx' with Meter ID 'SW4DM0101'
Sheet 'JP Nagar 1st Phase SW4DM0102' saved to 'data/SplitMeterIDFiles/SW4DM0102.xlsx' with Meter ID 'SW4DM0102'
Sheet 'JP Nagar 1st Phase SW4DM0103' saved to 'data/SplitMeterIDFiles/SW4DM0103.xlsx' with Meter ID 'SW4DM0103'
Sheet 'JP Nagar 2nd Phase SW4DM0201' saved to 'data/SplitMeterIDFiles/SW4DM0201.xlsx' with Meter ID 'SW4DM0201'
Sheet 'JP Nagar 3rd Phase SW4DM0302' saved to 'data/SplitMeterIDFiles/SW4DM0302.xlsx' with Meter ID 'SW4DM0302'
Sheet 'JP Nagar 3rd Phase SW4DM0301' saved to 'data/SplitMeterIDFiles/SW4DM0301.xlsx' with Meter ID 'SW4DM0301'
Sheet 'JP Nagar V Phase S2DM0201' saved to 'data/SplitMeterIDFiles/S2DM0201.xlsx' with Meter ID 'S2DM0201'
Sheet 'JP Nagar V Phase S2DM0202' saved to 'data/SplitMeterIDFiles/S2DM0202.xlsx' with Meter ID 'S2DM0202'
Sheet 'JP Nagar V Phase S2DM0203' saved to 'data/SplitMeterIDFiles/S2DM0203.xlsx' with Meter ID 'S2DM0203'
Sheet 'KRMarketChamarajpeteSW1DM0602  ' saved to 'data/SplitMeterIDFiles/KRMarketChamarajpeteSW1DM0602.xlsx' with Meter ID 'KRMarketChamarajpeteSW1DM0602'
Sheet 'KRMarketChamarajpeteSW1DM0603' saved to 'data/SplitMeterIDFiles/KRMarketChamarajpeteSW1DM0603.xlsx' with Meter ID 'KRMarketChamarajpeteSW1DM0603'
Sheet 'KRMarketChamarajpeteSW1SM0607' saved to 'data/SplitMeterIDFiles/KRMarketChamarajpeteSW1SM0607.xlsx' with Meter ID 'KRMarketChamarajpeteSW1SM0607'
Sheet 'KRMarketChamarajpeteSW1SM0606' saved to 'data/SplitMeterIDFiles/KRMarketChamarajpeteSW1SM0606.xlsx' with Meter ID 'KRMarketChamarajpeteSW1SM0606'
Sheet 'Kalidasa Layout SW3DM0101' saved to 'data/SplitMeterIDFiles/SW3DM0101.xlsx' with Meter ID 'SW3DM0101'
Sheet 'Kamkya Layout SW2DM1701' saved to 'data/SplitMeterIDFiles/SW2DM1701.xlsx' with Meter ID 'SW2DM1701'
Sheet 'Kathriguppe SW2DM0401' saved to 'data/SplitMeterIDFiles/SW2DM0401.xlsx' with Meter ID 'SW2DM0401'
Sheet 'Kathriguppe SW2DM0404' saved to 'data/SplitMeterIDFiles/SW2DM0404.xlsx' with Meter ID 'SW2DM0404'
Sheet 'Kathriguppe SW2DM0402' saved to 'data/SplitMeterIDFiles/SW2DM0402.xlsx' with Meter ID 'SW2DM0402'
Sheet 'Kathriguppe SW2DM0403' saved to 'data/SplitMeterIDFiles/SW2DM0403.xlsx' with Meter ID 'SW2DM0403'
Sheet 'KG Nagara SW1DM0102' saved to 'data/SplitMeterIDFiles/SW1DM0102.xlsx' with Meter ID 'SW1DM0102'
Sheet 'KG Nagara SW1DM0103' saved to 'data/SplitMeterIDFiles/SW1DM0103.xlsx' with Meter ID 'SW1DM0103'
Sheet 'KHB Colony SE3DM0401' saved to 'data/SplitMeterIDFiles/SE3DM0401.xlsx' with Meter ID 'SE3DM0401'
Sheet 'Koramangala 1st Block SE3DM1201' saved to 'data/SplitMeterIDFiles/SE3DM1201.xlsx' with Meter ID 'SE3DM1201'
Sheet 'Koramangala 1st Block SE3DM1202' saved to 'data/SplitMeterIDFiles/SE3DM1202.xlsx' with Meter ID 'SE3DM1202'
Sheet 'Koramangala 3rd & 4th SE3DM0301' saved to 'data/SplitMeterIDFiles/SE3DM0301.xlsx' with Meter ID 'SE3DM0301'
Sheet 'Koramangala 3rd & 4th SE3DM0302' saved to 'data/SplitMeterIDFiles/SE3DM0302.xlsx' with Meter ID 'SE3DM0302'
Sheet 'Koramangala 3rd & 4th SE3DM0304' saved to 'data/SplitMeterIDFiles/SE3DM0304.xlsx' with Meter ID 'SE3DM0304'
Sheet 'Koramangala6thBlk SE3DM0501' saved to 'data/SplitMeterIDFiles/SE3DM0501.xlsx' with Meter ID 'SE3DM0501'
Sheet 'Koramangala6thBlk SE3DM0502' saved to 'data/SplitMeterIDFiles/SE3DM0502.xlsx' with Meter ID 'SE3DM0502'
Sheet 'Kormangala 7th & 8th SE3DM1101' saved to 'data/SplitMeterIDFiles/SE3DM1101.xlsx' with Meter ID 'SE3DM1101'
Sheet 'Kormangala 7th & 8th SE3DM0201' saved to 'data/SplitMeterIDFiles/SE3DM0201.xlsx' with Meter ID 'SE3DM0201'
Sheet 'Kormangala 7th & 8th SE3DM0202' saved to 'data/SplitMeterIDFiles/SE3DM0202.xlsx' with Meter ID 'SE3DM0202'
Sheet 'KSRP Quarters SE3DM1301' saved to 'data/SplitMeterIDFiles/SE3DM1301.xlsx' with Meter ID 'SE3DM1301'
Sheet 'Kumarswamy Layout 1st S1DM0901' saved to 'data/SplitMeterIDFiles/S1DM0901.xlsx' with Meter ID 'S1DM0901'
Sheet 'Kumarswamy Layout 1st S1DM0902' saved to 'data/SplitMeterIDFiles/S1DM0902.xlsx' with Meter ID 'S1DM0902'
Sheet 'Kumarswamy Layout 2nd S1DM0601' saved to 'data/SplitMeterIDFiles/S1DM0601.xlsx' with Meter ID 'S1DM0601'

Sheet 'Kuvempu Nagar S3DM0301' saved to 'data/SplitMeterIDFiles/S3DM0301.xlsx' with Meter ID 'S3DM0301'
Sheet 'Kuvempu Nagar S3DM0302' saved to 'data/SplitMeterIDFiles/S3DM0302.xlsx' with Meter ID 'S3DM0302'
Sheet 'Kuvempu Nagar S3DM0303' saved to 'data/SplitMeterIDFiles/S3DM0303.xlsx' with Meter ID 'S3DM0303'
Sheet 'Madiwala S3DM0101' saved to 'data/SplitMeterIDFiles/S3DM0101.xlsx' with Meter ID 'S3DM0101'
Sheet 'Madiwala S3DM0102' saved to 'data/SplitMeterIDFiles/S3DM0102.xlsx' with Meter ID 'S3DM0102'
Sheet 'Maruthi Nagar S3DM0901' saved to 'data/SplitMeterIDFiles/S3DM0901.xlsx' with Meter ID 'S3DM0901'
Sheet 'Mavalli SW1DM0501' saved to 'data/SplitMeterIDFiles/SW1DM0501.xlsx' with Meter ID 'SW1DM0501'
Sheet 'Mavalli SW1DM0502' saved to 'data/SplitMeterIDFiles/SW1DM0502.xlsx' with Meter ID 'SW1DM0502'
Sheet 'Mico Layout S3DM0401' saved to 'data/SplitMeterIDFiles/S3DM0401.xlsx' with Meter ID 'S3DM0401'
Sheet 'Muneshwara Block SW3DM0704' saved to 'data/SplitMeterIDFiles/SW3DM0704.xlsx' with Meter ID 'SW3DM0704'
Sheet 'Muneshwara Block SW3DM0702' saved to 'data/SplitMeterIDFiles/SW3DM0702.xlsx' with Meter ID 'SW3DM0702'
Sheet 'Muneshwara Block SW3DM0701' saved to 'data/SplitMeterIDFiles/SW3DM0701.xlsx' with Meter ID 'SW3DM0701'
Sheet 'Nagendra Block SW3DM0401' saved to 'data/SplitMeterIDFiles/SW3DM0401.xlsx' with Meter ID 'SW3DM0401'
Sheet 'Nagendra Block SW3DM0402' saved to 'data/SplitMeterIDFiles/SW3DM0402.xlsx' with Meter ID 'SW3DM0402'
Sheet 'New Timber Yard  W1DMA0202' saved to 'data/SplitMeterIDFiles/W1DMA0202.xlsx' with Meter ID 'W1DMA0202'
Sheet 'New Timber Yard  W1DMA0201' saved to 'data/SplitMeterIDFiles/W1DMA0201.xlsx' with Meter ID 'W1DMA0201'
Sheet 'New Timber Yard  W1DMA0203' saved to 'data/SplitMeterIDFiles/W1DMA0203.xlsx' with Meter ID 'W1DMA0203'
Sheet 'New Timber Yard  W1DMA0204' saved to 'data/SplitMeterIDFiles/W1DMA0204.xlsx' with Meter ID 'W1DMA0204'
Sheet 'Newguddadahalli W1DM0102' saved to 'data/SplitMeterIDFiles/W1DM0102.xlsx' with Meter ID 'W1DM0102'
Sheet 'Newguddadahalli W1DM0103' saved to 'data/SplitMeterIDFiles/W1DM0103.xlsx' with Meter ID 'W1DM0103'
Sheet 'Newguddadahalli W1DM0101' saved to 'data/SplitMeterIDFiles/W1DM0101.xlsx' with Meter ID 'W1DM0101'
Sheet 'Old Guddadahalli SW1DM1001' saved to 'data/SplitMeterIDFiles/SW1DM1001.xlsx' with Meter ID 'SW1DM1001'
Sheet 'Old Guddadahalli SW1DM1002' saved to 'data/SplitMeterIDFiles/SW1DM1002.xlsx' with Meter ID 'SW1DM1002'
Sheet 'Padmanabhanaga S1DM0301' saved to 'data/SplitMeterIDFiles/S1DM0301.xlsx' with Meter ID 'S1DM0301'
Sheet 'Padmanabhanagar S1DM0302 ' saved to 'data/SplitMeterIDFiles/S1DM0302.xlsx' with Meter ID 'S1DM0302'
Sheet 'Pragathipura S1DM1001' saved to 'data/SplitMeterIDFiles/S1DM1001.xlsx' with Meter ID 'S1DM1001'
Sheet 'Pragathipura S1DM1002' saved to 'data/SplitMeterIDFiles/S1DM1002.xlsx' with Meter ID 'S1DM1002'
Sheet 'Pragathipura S1DM1003' saved to 'data/SplitMeterIDFiles/S1DM1003.xlsx' with Meter ID 'S1DM1003'
Sheet 'Raghavendra Block SW3DM0201' saved to 'data/SplitMeterIDFiles/SW3DM0201.xlsx' with Meter ID 'SW3DM0201'
Sheet 'Shakambari Nagar SW4DM0801' saved to 'data/SplitMeterIDFiles/SW4DM0801.xlsx' with Meter ID 'SW4DM0801'
Sheet 'Shakambari Nagar SW4DM0802' saved to 'data/SplitMeterIDFiles/SW4DM0802.xlsx' with Meter ID 'SW4DM0802'
Sheet 'Shakambari Nagar SW4SM0801' saved to 'data/SplitMeterIDFiles/SW4SM0801.xlsx' with Meter ID 'SW4SM0801'
Sheet 'Shastri Nagar SW2DM1101' saved to 'data/SplitMeterIDFiles/SW2DM1101.xlsx' with Meter ID 'SW2DM1101'
Sheet 'Shastri Nagar SW2DM1102' saved to 'data/SplitMeterIDFiles/SW2DM1102.xlsx' with Meter ID 'SW2DM1102'
Sheet 'Shastri Nagar SW2DM1103' saved to 'data/SplitMeterIDFiles/SW2DM1103.xlsx' with Meter ID 'SW2DM1103'
Sheet 'Siddhartha Colony SE3DM0802' saved to 'data/SplitMeterIDFiles/SE3DM0802.xlsx' with Meter ID 'SE3DM0802'
Sheet 'Siddhartha Colony SE3DM0801' saved to 'data/SplitMeterIDFiles/SE3DM0801.xlsx' with Meter ID 'SE3DM0801'
Sheet 'Siddhartha Colony SE3BM0801' saved to 'data/SplitMeterIDFiles/SE3BM0801.xlsx' with Meter ID 'SE3BM0801'
Sheet 'Siddhartha Colony SE3BM0802' saved to 'data/SplitMeterIDFiles/SE3BM0802.xlsx' with Meter ID 'SE3BM0802'
Sheet 'Siddhartha Colony SE3BM0803' saved to 'data/SplitMeterIDFiles/SE3BM0803.xlsx' with Meter ID 'SE3BM0803'
Sheet 'Srinagar SW3DM0301' saved to 'data/SplitMeterIDFiles/SW3DM0301.xlsx' with Meter ID 'SW3DM0301'
Sheet 'Srinagar SW3DM0302' saved to 'data/SplitMeterIDFiles/SW3DM0302.xlsx' with Meter ID 'SW3DM0302'
Sheet 'Srinagar SW3DM0303' saved to 'data/SplitMeterIDFiles/SW3DM0303.xlsx' with Meter ID 'SW3DM0303'
Sheet 'Srinivasa Nagar SW2DM0302.' saved to 'data/SplitMeterIDFiles/SW2DM0302..xlsx' with Meter ID 'SW2DM0302.'
Sheet 'Sheet33' saved to 'data/SplitMeterIDFiles/Sheet33.xlsx' with Meter ID 'Sheet33'
Sheet 'Srinivasa Nagar SW2DM0304' saved to 'data/SplitMeterIDFiles/SW2DM0304.xlsx' with Meter ID 'SW2DM0304'
Sheet 'Srinivasa Nagar SW2DM0301' saved to 'data/SplitMeterIDFiles/SW2DM0301.xlsx' with Meter ID 'SW2DM0301'
Sheet 'Srinivasa Nagar SW2DM0303' saved to 'data/SplitMeterIDFiles/SW2DM0303.xlsx' with Meter ID 'SW2DM0303'
Sheet 'STB SE3DM0601' saved to 'data/SplitMeterIDFiles/SE3DM0601.xlsx' with Meter ID 'SE3DM0601'
Sheet 'STB SE3DM0602' saved to 'data/SplitMeterIDFiles/SE3DM0602.xlsx' with Meter ID 'SE3DM0602'
Sheet 'Suddagunte Palya S3DM0804 ' saved to 'data/SplitMeterIDFiles/S3DM0804.xlsx' with Meter ID 'S3DM0804'
Sheet 'Suddagunte Palya S3DM0803' saved to 'data/SplitMeterIDFiles/S3DM0803.xlsx' with Meter ID 'S3DM0803'
Sheet 'Suddagunte Palya S3DM0802' saved to 'data/SplitMeterIDFiles/S3DM0802.xlsx' with Meter ID 'S3DM0802'
Sheet 'Suddagunte Palya S3DM0801' saved to 'data/SplitMeterIDFiles/S3DM0801.xlsx' with Meter ID 'S3DM0801'
Sheet 'Suddagunte Palya S3DM0805' saved to 'data/SplitMeterIDFiles/S3DM0805.xlsx' with Meter ID 'S3DM0805'
Sheet 'Thyagaraja Nagar SW3DM1301' saved to 'data/SplitMeterIDFiles/SW3DM1301.xlsx' with Meter ID 'SW3DM1301'
Sheet 'Thyagaraja Nagar SW3DM1302' saved to 'data/SplitMeterIDFiles/SW3DM1302.xlsx' with Meter ID 'SW3DM1302'
Sheet 'Thyagaraja Nagar SW3DM1303' saved to 'data/SplitMeterIDFiles/SW3DM1303.xlsx' with Meter ID 'SW3DM1303'
Sheet 'Thyagaraja Nagar SW3DM1304' saved to 'data/SplitMeterIDFiles/SW3DM1304.xlsx' with Meter ID 'SW3DM1304'
Sheet 'Thyagaraja Nagar SW3DM1306' saved to 'data/SplitMeterIDFiles/SW3DM1306.xlsx' with Meter ID 'SW3DM1306'
Sheet 'Thyagaraja Nagar SW3DM1308' saved to 'data/SplitMeterIDFiles/SW3DM1308.xlsx' with Meter ID 'SW3DM1308'
Sheet 'V V Puram SW1DM0402' saved to 'data/SplitMeterIDFiles/SW1DM0402.xlsx' with Meter ID 'SW1DM0402'
Sheet 'V V Puram SW1DM0403' saved to 'data/SplitMeterIDFiles/SW1DM0403.xlsx' with Meter ID 'SW1DM0403'
Sheet 'V V Puram SW1DM0405' saved to 'data/SplitMeterIDFiles/SW1DM0405.xlsx' with Meter ID 'SW1DM0405'
Sheet 'Venkateshwar Layout S3DM0501' saved to 'data/SplitMeterIDFiles/S3DM0501.xlsx' with Meter ID 'S3DM0501'
Sheet 'Venkateshwar Layout S3DM0502' saved to 'data/SplitMeterIDFiles/S3DM0502.xlsx' with Meter ID 'S3DM0502'
Sheet 'Venkateshwar Layout S3DM0503' saved to 'data/SplitMeterIDFiles/S3DM0503.xlsx' with Meter ID 'S3DM0503'
Sheet 'Vidya Nagar SW2DM0102' saved to 'data/SplitMeterIDFiles/SW2DM0102.xlsx' with Meter ID 'SW2DM0102'
Sheet 'Vidya Nagar SW2DM0101' saved to 'data/SplitMeterIDFiles/SW2DM0101.xlsx' with Meter ID 'SW2DM0101'
Sheet 'Vivekananda Nagar SW2DM0501' saved to 'data/SplitMeterIDFiles/SW2DM0501.xlsx' with Meter ID 'SW2DM0501'
Sheet 'Venkateshwar Layout S3SM0501' saved to 'data/SplitMeterIDFiles/S3SM0501.xlsx' with Meter ID 'S3SM0501'
All sheets processed successfully.
File 'data/SplitMeterIDFiles/Byatarayanap.xlsx' removed.
File 'data/SplitMeterIDFiles/Nagar.xlsx' removed.
File 'data/SplitMeterIDFiles/KRMarketChamarajpeteSW1DM0602.xlsx' removed.
File 'data/SplitMeterIDFiles/KRMarketChamarajpeteSW1DM0603.xlsx' removed.
File 'data/SplitMeterIDFiles/KRMarketChamarajpeteSW1SM0607.xlsx' removed.
File 'data/SplitMeterIDFiles/KRMarketChamarajpeteSW1SM0606.xlsx' removed.
File 'data/SplitMeterIDFiles/SW3toSW1.xlsx' removed.
File 'data/SplitMeterIDFiles/Sheet33.xlsx' removed.

In [4]:
# Load the WaterLekageDF.csv dataframe
water_leakage_df = pd.read_csv("data/WaterLekageDF.csv")

# Iterate over each unique leak ID
for index, row in water_leakage_df.iterrows():
    concatenated_df = pd.DataFrame()
    # Extracting meter IDs associated with the current leak ID
    meter_ids = row[['metre_1', 'meter_2', 'meter_3', 'meter_4', 'meter_5', 'meter_6']].values
    meter_ids = [meter_id for meter_id in meter_ids if pd.notnull(meter_id)]  # Remove null values
    print(f"Leak ID: {row['id']}, Meter IDs: {meter_ids}") # Printing leak ID and associated meter IDs
    directory = "data/SplitMeterIDFiles"
    # Iterate over each meter ID associated with the current leak ID
    for meter_id in meter_ids:
        file_path = os.path.join(directory, f"{meter_id}.xlsx")   # Constructing the file path
        if os.path.exists(file_path):  # Checking if the file exists
            print(f"Reading data from {file_path}")
            df = pd.read_excel(file_path)
            df = df.iloc[1:].reset_index(drop=True)  # Drop the first row
            df.columns = ['Date', 'Time', 'Flow Rate (mᶾ/hr)', 'Net Flow (mᶾ)', 'Pressure (m)', 'Meter ID']  # Assign new column names
            concatenated_df = pd.concat([concatenated_df, df], axis=0, ignore_index=True)
            
        else:
            print(f"File {file_path} not found.")
    concatenated_df.insert(0, 'Leak ID', index+1)
    output_directory = "data/RawLeakData"
    if not os.path.exists(output_directory):
        os.makedirs(output_directory)
    
    output_csv_path = os.path.join(output_directory, f"{row['id']}.csv")
    concatenated_df.to_csv(output_csv_path, index=False)

    print(f"Concatenated meter data for leak {row['id']} saved to:", output_csv_path)

Leak ID: 2377, Meter IDs: ['SE3DM0602', 'SE3DM0601', 'SE3DM0303', 'SE3DM0304', 'SE3DM0501', 'SE3DM0401']
Reading data from data/SplitMeterIDFiles/SE3DM0602.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0601.xlsx
File data/SplitMeterIDFiles/SE3DM0303.xlsx not found.
Reading data from data/SplitMeterIDFiles/SE3DM0304.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0501.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0401.xlsx
Concatenated meter data for leak 2377 saved to: data/RawLeakData/2377.csv
Leak ID: 2721, Meter IDs: ['SE3DM0602', 'SE3DM0601', 'SE3DM0303', 'SE3DM0304', 'SE3DM0501', 'SE3DM0401']
Reading data from data/SplitMeterIDFiles/SE3DM0602.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0601.xlsx
File data/SplitMeterIDFiles/SE3DM0303.xlsx not found.
Reading data from data/SplitMeterIDFiles/SE3DM0304.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0501.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0401.xlsx
Concatenated meter data for leak 2721 saved to: data/RawLeakData/2721.csv
Leak ID: 4820, Meter IDs: ['SE3DM0301', 'SE3DM0302', 'SE3DM0802', 'SE3DM0801', 'SE3DM0401', 'SE3DM0501']
Reading data from data/SplitMeterIDFiles/SE3DM0301.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0302.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0802.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0801.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0401.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0501.xlsx
Concatenated meter data for leak 4820 saved to: data/RawLeakData/4820.csv
Leak ID: 4814, Meter IDs: ['SE3DM0301', 'SE3DM0302', 'SE3DM0802', 'SE3DM0801', 'SE3DM0401', 'SE3DM0501']
Reading data from data/SplitMeterIDFiles/SE3DM0301.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0302.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0802.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0801.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0401.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0501.xlsx
Concatenated meter data for leak 4814 saved to: data/RawLeakData/4814.csv
Leak ID: 1304, Meter IDs: ['SE3DM0301', 'SE3DM0302', 'SE3DM0802', 'SE3DM0801', 'SE3DM0401', 'SE3DM0501']
Reading data from data/SplitMeterIDFiles/SE3DM0301.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0302.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0802.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0801.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0401.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0501.xlsx
Concatenated meter data for leak 1304 saved to: data/RawLeakData/1304.csv
Leak ID: 4209, Meter IDs: ['SE3DM0702', 'SE3DM0703', 'SE3DM0701', 'SE3DM1202', 'SE3DM1301', 'SE3DM0704']
Reading data from data/SplitMeterIDFiles/SE3DM0702.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0703.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0701.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM1202.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM1301.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0704.xlsx
Concatenated meter data for leak 4209 saved to: data/RawLeakData/4209.csv
Leak ID: 4205, Meter IDs: ['SE3DM0702', 'SE3DM0703', 'SE3DM0701', 'SE3DM1202', 'SE3DM1301', 'SE3DM0704']
Reading data from data/SplitMeterIDFiles/SE3DM0702.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0703.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0701.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM1202.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM1301.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0704.xlsx
Concatenated meter data for leak 4205 saved to: data/RawLeakData/4205.csv
Leak ID: 4344, Meter IDs: ['SE3DM0702', 'SE3DM0703', 'SE3DM0701', 'SE3DM1202', 'SE3DM1301', 'SE3DM0704']
Reading data from data/SplitMeterIDFiles/SE3DM0702.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0703.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0701.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM1202.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM1301.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0704.xlsx
Concatenated meter data for leak 4344 saved to: data/RawLeakData/4344.csv
Leak ID: 2464, Meter IDs: ['SE3DM0202', 'S3DM0805', 'SE3DM0101', 'SW4SM0701', 'SW4SM0702', 'S3DM0804']
Reading data from data/SplitMeterIDFiles/SE3DM0202.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0805.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0101.xlsx
Reading data from data/SplitMeterIDFiles/SW4SM0701.xlsx
Reading data from data/SplitMeterIDFiles/SW4SM0702.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0804.xlsx
Concatenated meter data for leak 2464 saved to: data/RawLeakData/2464.csv
Leak ID: 3925, Meter IDs: ['SE3DM0202', 'S3DM0805', 'SE3DM0101', 'SW4SM0701', 'SW4SM0702', 'S3DM0804']
Reading data from data/SplitMeterIDFiles/SE3DM0202.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0805.xlsx
Reading data from data/SplitMeterIDFiles/SE3DM0101.xlsx
Reading data from data/SplitMeterIDFiles/SW4SM0701.xlsx
Reading data from data/SplitMeterIDFiles/SW4SM0702.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0804.xlsx
Concatenated meter data for leak 3925 saved to: data/RawLeakData/3925.csv
Leak ID: 5956, Meter IDs: ['S3DM0501', 'S3DM0201', 'S3DM0202', 'S3DM0304', 'S3DM0502', 'S3DM0605']
Reading data from data/SplitMeterIDFiles/S3DM0501.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0202.xlsx
File data/SplitMeterIDFiles/S3DM0304.xlsx not found.
Reading data from data/SplitMeterIDFiles/S3DM0502.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0605.xlsx
Concatenated meter data for leak 5956 saved to: data/RawLeakData/5956.csv
Leak ID: 563, Meter IDs: ['S3DM0501', 'S3DM0201', 'S3DM0202', 'S3DM0304', 'S3DM0502', 'S3DM0605']
Reading data from data/SplitMeterIDFiles/S3DM0501.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0202.xlsx
File data/SplitMeterIDFiles/S3DM0304.xlsx not found.
Reading data from data/SplitMeterIDFiles/S3DM0502.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0605.xlsx
Concatenated meter data for leak 563 saved to: data/RawLeakData/563.csv
Leak ID: 5018, Meter IDs: ['S3DM0501', 'S3DM0201', 'S3DM0202', 'S3DM0304', 'S3DM0502', 'S3DM0605']
Reading data from data/SplitMeterIDFiles/S3DM0501.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0202.xlsx
File data/SplitMeterIDFiles/S3DM0304.xlsx not found.
Reading data from data/SplitMeterIDFiles/S3DM0502.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0605.xlsx
Concatenated meter data for leak 5018 saved to: data/RawLeakData/5018.csv
Leak ID: 269, Meter IDs: ['S3DM0501', 'S3DM0201', 'S3DM0202', 'S3DM0304', 'S3DM0502', 'S3DM0605']
Reading data from data/SplitMeterIDFiles/S3DM0501.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0202.xlsx
File data/SplitMeterIDFiles/S3DM0304.xlsx not found.
Reading data from data/SplitMeterIDFiles/S3DM0502.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0605.xlsx
Concatenated meter data for leak 269 saved to: data/RawLeakData/269.csv
Leak ID: 272, Meter IDs: ['S3DM0303', 'S3DM0601', 'S3DM0605', 'S3DM0502', 'S3DM0503', 'S3DM0302']
Reading data from data/SplitMeterIDFiles/S3DM0303.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0601.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0605.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0502.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0503.xlsx
Reading data from data/SplitMeterIDFiles/S3DM0302.xlsx
Concatenated meter data for leak 272 saved to: data/RawLeakData/272.csv
Leak ID: 53, Meter IDs: ['SW4SM1101', 'SW4SM1103', 'SW4DM0502', 'SW4DM1102', 'SW4DM0301', 'SW4DM0201']
Reading data from data/SplitMeterIDFiles/SW4SM1101.xlsx
Reading data from data/SplitMeterIDFiles/SW4SM1103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0502.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0301.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0201.xlsx
Concatenated meter data for leak 53 saved to: data/RawLeakData/53.csv
Leak ID: 794, Meter IDs: ['SW4SM1101', 'SW4SM1103', 'SW4DM0502', 'SW4DM1102', 'SW4DM0301', 'SW4DM0201']
Reading data from data/SplitMeterIDFiles/SW4SM1101.xlsx

Reading data from data/SplitMeterIDFiles/SW4SM1103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0502.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0301.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0201.xlsx
Concatenated meter data for leak 794 saved to: data/RawLeakData/794.csv
Leak ID: 494, Meter IDs: ['SW4SM1101', 'SW4SM1103', 'SW4DM0502', 'SW4DM1102', 'SW4DM0301', 'SW4DM0201']
Reading data from data/SplitMeterIDFiles/SW4SM1101.xlsx
Reading data from data/SplitMeterIDFiles/SW4SM1103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0502.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0301.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0201.xlsx
Concatenated meter data for leak 494 saved to: data/RawLeakData/494.csv
Leak ID: 547, Meter IDs: ['SW4SM1101', 'SW4SM1103', 'SW4DM0502', 'SW4DM1102', 'SW4DM0301', 'SW4DM0201']
Reading data from data/SplitMeterIDFiles/SW4SM1101.xlsx
Reading data from data/SplitMeterIDFiles/SW4SM1103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0502.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0301.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0201.xlsx
Concatenated meter data for leak 547 saved to: data/RawLeakData/547.csv
Leak ID: 3730, Meter IDs: ['S2DM0202', 'S2DM0201', 'S2DM0102', 'S2DM0203', 'SW4DM0104', 'SW4DM0103']
Reading data from data/SplitMeterIDFiles/S2DM0202.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0102.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Concatenated meter data for leak 3730 saved to: data/RawLeakData/3730.csv
Leak ID: 3714, Meter IDs: ['S2DM0202', 'S2DM0201', 'S2DM0102', 'S2DM0203', 'SW4DM0104', 'SW4DM0103']
Reading data from data/SplitMeterIDFiles/S2DM0202.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0102.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Concatenated meter data for leak 3714 saved to: data/RawLeakData/3714.csv
Leak ID: 3766, Meter IDs: ['S2DM0202', 'S2DM0201', 'S2DM0102', 'S2DM0203', 'SW4DM0104', 'SW4DM0103']
Reading data from data/SplitMeterIDFiles/S2DM0202.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0102.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Concatenated meter data for leak 3766 saved to: data/RawLeakData/3766.csv
Leak ID: 3733, Meter IDs: ['S2DM0202', 'S2DM0201', 'S2DM0102', 'S2DM0203', 'SW4DM0104', 'SW4DM0103']
Reading data from data/SplitMeterIDFiles/S2DM0202.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0102.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Concatenated meter data for leak 3733 saved to: data/RawLeakData/3733.csv
Leak ID: 4827, Meter IDs: ['S2DM0202', 'S2DM0201', 'S2DM0102', 'S2DM0203', 'SW4DM0104', 'SW4DM0103']
Reading data from data/SplitMeterIDFiles/S2DM0202.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0201.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0102.xlsx
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Concatenated meter data for leak 4827 saved to: data/RawLeakData/4827.csv
Leak ID: 3168, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 3168 saved to: data/RawLeakData/3168.csv
Leak ID: 479, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 479 saved to: data/RawLeakData/479.csv
Leak ID: 719, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 719 saved to: data/RawLeakData/719.csv
Leak ID: 713, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 713 saved to: data/RawLeakData/713.csv
Leak ID: 585, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 585 saved to: data/RawLeakData/585.csv
Leak ID: 3912, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 3912 saved to: data/RawLeakData/3912.csv
Leak ID: 4034, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 4034 saved to: data/RawLeakData/4034.csv
Leak ID: 3999, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 3999 saved to: data/RawLeakData/3999.csv
Leak ID: 3265, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx

Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 3265 saved to: data/RawLeakData/3265.csv
Leak ID: 7248, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 7248 saved to: data/RawLeakData/7248.csv
Leak ID: 7615, Meter IDs: ['S2DM0203', 'SW4DM0104', 'SW4DM0103', 'SW4DM0102', 'SW4DM0101', 'S1DM1003']
Reading data from data/SplitMeterIDFiles/S2DM0203.xlsx
File data/SplitMeterIDFiles/SW4DM0104.xlsx not found.
Reading data from data/SplitMeterIDFiles/SW4DM0103.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0102.xlsx
Reading data from data/SplitMeterIDFiles/SW4DM0101.xlsx
Reading data from data/SplitMeterIDFiles/S1DM1003.xlsx
Concatenated meter data for leak 7615 saved to: data/RawLeakData/7615.csv
Leak ID: 6999, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 6999 saved to: data/RawLeakData/6999.csv
Leak ID: 284, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 284 saved to: data/RawLeakData/284.csv
Leak ID: 5780, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 5780 saved to: data/RawLeakData/5780.csv
Leak ID: 239, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 239 saved to: data/RawLeakData/239.csv
Leak ID: 927, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 927 saved to: data/RawLeakData/927.csv
Leak ID: 3350, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 3350 saved to: data/RawLeakData/3350.csv
Leak ID: 4378, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 4378 saved to: data/RawLeakData/4378.csv
Leak ID: 3643, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 3643 saved to: data/RawLeakData/3643.csv
Leak ID: 3465, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 3465 saved to: data/RawLeakData/3465.csv
Leak ID: 1299, Meter IDs: ['SW2DM1001', 'SW2DM1001', 'SW2DM1102', 'SW2DM1008', 'SW2DM1101', 'SW2SM1201']
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1001.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1102.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1008.xlsx
Reading data from data/SplitMeterIDFiles/SW2DM1101.xlsx
File data/SplitMeterIDFiles/SW2SM1201.xlsx not found.
Concatenated meter data for leak 1299 saved to: data/RawLeakData/1299.csv